name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout cod
      uses: actions/checkout@v3

    # Backend Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Backend
      run: ./mvnw clean install

    - name: Run Backend Tests
      run: ./mvnw test

    # Frontend React
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Frontend dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build Frontend
      run: npm run build
      working-directory: ./frontend

    - name: Run Frontend Tests
      run: npm test -- --watchAll=false
      working-directory: ./frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Deploy (exemplu simplu)
      run: echo "Deploy pe server..."
